services:
  apiserver:
    build:
      context: .
      dockerfile: ./deploy/apiserver/Dockerfile
      target: dev
    container_name: apiserver
    restart: on-failure
    ports:
    - "8080:8080"
    environment:
      APP_VERSION: "development"
      LOGURU_LEVEL: "DEBUG"
    volumes:
      - ./src/api:/code

